# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65d7187610407cdd5e00d76690518078870e29a6739e8a97bb4b600bac276be826d99c1c8dc2b19aca05e54bf4de07369c2b12f05028b26079c9a3e31c124f49

test:
  secret_key_base: a59ec549e9f0dd30ee6c8e6f2f0e16baa872be08637d6195ab86f41d33099d29aa881be32a01e6801060a500fa116706ee95d7d337e7a1ea25338bfca2c23f79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
